remote_theme: pages-themes/minimal@v0.2.0
image: docs/assets/circle.png
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Portfolio
description: Putting myself out there
show_downloads: false
